
.PHONE: all clean build

all: build

build:
	@make -s -C libstub0 build
	@make -s -C lib0 build
	@make -s -C barebones build

clean:
	@make -s -C libstub0 clean
	@make -s -C lib0 clean
	@make -s -C barebones clean
